# Generated by Django 5.2.8 on 2026-01-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/def_img.jpg', upload_to='profile_images'),
        ),
    ]
